COMP: Do not use constexpr in ITKImageProcessingImportImageStackTest
Causes build errors with VS2013:

  C:\Dashboards\DREAM3D_Plugins\ItkImageProcessing\Test\ITKImageProcessingImportImageStackTest.cpp(62)
  : error C2144: syntax error : 'unsigned int' should be preceded by ';'